
import {CarritoProvider} from '@/context/CarritoContext'
import Head from 'next/head'
import { Header } from '@/components/Header'
import { Inter, Barlow } from 'next/font/google'
import './globals.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

const barlow = Barlow({ subsets: ['latin'], weight:['300','400','500','700','900'], variable: '--font-barlow' })

export default function RootLayout({ children }) {
  return (
    
    <html lang="es" className={barlow.className}>
      <Head>
        <title>Guitars</title>
      </Head>
      <body className=' bg-slate-100'>
      <CarritoProvider>
        <Header />
        
        {children}
        </CarritoProvider>
        </body>
    </html>
  )
}
