
import {CarritoProvider} from '@/context/CarritoContext'
import Head from 'next/head'
import { Header } from '@/components/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="es">
      <Head>
        <title>Guitars</title>
      </Head>
      <body>
      <CarritoProvider>
        <Header />
        
        {children}
        </CarritoProvider>
        </body>
    </html>
  )
}
